---
apiVersion: v1
kind: Service
metadata:
  name: bookworm-rating
spec:
  type: ClusterIP
  selector:
    app: bookworm-rating
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
    - name: healthchecks
      port: 8004
      targetPort: 8004
