[build]
base = "docs/eventcatalog"
publish = "dist"
command = "pnpm run build"
environment = { NODE_OPTIONS = "--max-old-space-size=4096" }

[functions]
directory = "docs/eventcatalog/netlify/functions"

[[plugins]]
package = "@netlify/plugin-lighthouse"
