apiVersion: v1
data:
  ui_path: /
  HealthChecksUI__HealthChecks__0__Name: gateway
  HealthChecksUI__HealthChecks__0__Uri: gateway:8081/healthz
  HealthChecksUI__HealthChecks__1__Name: identity-api
  HealthChecksUI__HealthChecks__1__Uri: identity-api:8081/healthz
  HealthChecksUI__HealthChecks__2__Name: catalog-api
  HealthChecksUI__HealthChecks__2__Uri: catalog-api:8081/healthz
  HealthChecksUI__HealthChecks__3__Name: ordering-api
  HealthChecksUI__HealthChecks__3__Uri: ordering-api:8081/healthz
  HealthChecksUI__HealthChecks__4__Name: rating-api
  HealthChecksUI__HealthChecks__4__Uri: rating-api:8081/healthz
  HealthChecksUI__HealthChecks__5__Name: basket-api
  HealthChecksUI__HealthChecks__5__Uri: basket-api:8081/healthz
  HealthChecksUI__HealthChecks__6__Name: notification-api
  HealthChecksUI__HealthChecks__6__Uri: notification-api:8081/healthz
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: healthchecksui
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: healthchecksui
  name: healthchecksui